# Generated by Django 3.2 on 2021-05-02 06:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=250)),
                ('title_2', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Home Section',
            },
        ),
    ]
