# Generated by Django 3.2 on 2021-05-02 09:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayuraweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('content_1', ckeditor.fields.RichTextField(blank=True)),
                ('content_2', ckeditor.fields.RichTextField(blank=True)),
                ('content_3', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(upload_to='images/blog')),
            ],
            options={
                'verbose_name_plural': 'Blog Post',
            },
        ),
        migrations.CreateModel(
            name='MaterialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('sub_title', models.CharField(max_length=250)),
                ('image_1', models.ImageField(upload_to='images/homepage/materials')),
                ('name_1', models.CharField(max_length=250)),
                ('image_2', models.ImageField(upload_to='images/homepage/materials')),
                ('name_2', models.CharField(max_length=250)),
                ('image_3', models.ImageField(upload_to='images/homepage/materials')),
                ('name_3', models.CharField(max_length=250)),
                ('image_4', models.ImageField(upload_to='images/homepage/materials')),
                ('name_4', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Material Section',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/homepage/products')),
            ],
            options={
                'verbose_name_plural': 'Home Section',
            },
        ),
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Product Section',
            },
        ),
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('image_1', models.ImageField(upload_to='images/homepage/testimonials')),
                ('name_1', models.CharField(max_length=250)),
                ('prof_1', models.CharField(max_length=250)),
                ('content_1', ckeditor.fields.RichTextField(blank=True)),
                ('image_2', models.ImageField(upload_to='images/homepage/testimonials')),
                ('name_2', models.CharField(max_length=250)),
                ('prof_2', models.CharField(max_length=250)),
                ('content_2', ckeditor.fields.RichTextField(blank=True)),
                ('image_3', models.ImageField(upload_to='images/homepage/testimonials')),
                ('name_3', models.CharField(max_length=250)),
                ('prof_3', models.CharField(max_length=250)),
                ('content_3', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonial Section',
            },
        ),
        migrations.CreateModel(
            name='VideoBlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=250)),
                ('video_description', ckeditor.fields.RichTextField(blank=True)),
                ('video_url', models.CharField(max_length=1000)),
                ('blog_title', models.CharField(max_length=250)),
                ('blog_description', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Video & Blog Section',
            },
        ),
        migrations.AlterField(
            model_name='homesection',
            name='image',
            field=models.ImageField(upload_to='images/homepage'),
        ),
    ]
