# Generated by Django 3.2 on 2021-05-03 06:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayuraweb', '0002_auto_20210502_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoAreWe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=250)),
                ('title_2', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(upload_to='images/whoarewe')),
            ],
            options={
                'verbose_name_plural': 'Who Are We',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
    ]
