# Generated by Django 3.2 on 2021-05-03 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayuraweb', '0003_auto_20210503_0658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhoAreWe',
        ),
    ]
