# Generated by Django 3.2 on 2021-05-04 09:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mayuraweb', '0006_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor.fields.RichTextField(blank=True)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=250)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mayuraweb.blogpost')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
