# Generated by Django 3.2 on 2021-05-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayuraweb', '0007_auto_20210504_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='display_in_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
