# Generated by Django 3.2 on 2021-05-04 09:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayuraweb', '0008_auto_20210504_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=250)),
                ('title_2', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Page',
            },
        ),
    ]
