# Generated by Django 3.2 on 2021-05-04 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mayuraweb', '0009_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
